version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  web-service:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./service:/app
  web-client:
      build:
        context: .
        dockerfile: ./client/Dockerfile
      ports:
        - "3001:3000"
      volumes:
        - ./client:/app

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
