version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  express-app:
    image: node:18
    container_name: express-app
    working_dir: /service
    volumes:
      - ./service:/service
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    command: >
      sh -c " yarn install && yarn build && yarn start"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
